import pandas as pd
import requests
import json
import time
from datetime import datetime
from tqdm import tqdm
import re
import os

INPUT_FILE = "all_backports_openstack.csv"
OUTPUT_FILE = "all_backports_openstack_enriched_metrics.csv"

SAVE_EVERY = 50
SLEEP_BETWEEN_CALLS = 0.15
MAX_RETRIES = 3

session = requests.Session()
session.headers.update({
    "User-Agent": "IaC-Backport-Research-Script/4.0"
})

METRIC_COLUMNS = [
    # Master/original patch metrics
    "master_patchsets",
    "master_human_messages",
    "master_human_reviewers",
    "master_review_duration_days",
    "master_review_hours",
    "master_ci_failures",
    "master_human_negative_votes",
    "master_api_status",

    # Stable/backport patch metrics
    "bp_patchsets",
    "bp_human_messages",
    "bp_human_reviewers",
    "bp_review_duration_days",
    "bp_review_hours",
    "bp_ci_failures",
    "bp_human_negative_votes",
    "bp_api_status",
]



KNOWN_BOT_NAMES = {
    "Zuul",
    "Jenkins",
    "OpenStack Proposal Bot",
    "RDO CI",
    "Smaug CI",
    "openstack-ci",
    "Zuul CI",
}

BOT_KEYWORDS = [
    "bot",
    "ci",
    "zuul",
    "jenkins",
    "proposal",
]


def is_bot(author_name, tag=""):
    """
    Détecte si un message vient probablement d'un bot ou système CI.
    Cette fonction est plus robuste qu'une simple liste fixe de noms.
    """
    name = str(author_name or "").strip()
    name_lower = name.lower()
    tag_lower = str(tag or "").lower()

    if name in KNOWN_BOT_NAMES:
        return True

    if tag_lower.startswith("autogenerated"):
        return True

    if "autogenerated:zuul" in tag_lower:
        return True

    if any(keyword in name_lower for keyword in BOT_KEYWORDS):
        return True

    return False



def clean_gerrit_json(raw_text):
    """
    Supprime le préfixe anti-XSSI de Gerrit.
    Gerrit retourne souvent une réponse qui commence par )]}'
    """
    if raw_text.startswith(")]}'"):
        return raw_text[4:].strip()
    return raw_text


def get_numeric_id(url):
    """
    Extrait l'identifiant numérique Gerrit depuis une URL de type :
    https://review.opendev.org/c/project/name/+/940963
    """
    match = re.search(r"\+/(\d+)", str(url))
    return match.group(1) if match else None


def parse_gerrit_datetime(value):
    """
    Convertit une date Gerrit en objet datetime.

    Exemple Gerrit :
    2024-12-10 09:33:21.000000000

    Certaines réponses peuvent contenir 6 ou 9 chiffres après la seconde.
    Python datetime supporte 6 chiffres pour les microsecondes.
    """
    if not value:
        return None

    value = str(value).strip()

    # Supprimer le suffixe timezone éventuel
    value = value.replace("Z", "")

    # Garder seulement les 6 premiers chiffres des fractions de secondes
    if "." in value:
        main, frac = value.split(".", 1)
        frac = re.sub(r"\D", "", frac)
        frac = frac[:6].ljust(6, "0")
        value = f"{main}.{frac}"
        fmt = "%Y-%m-%d %H:%M:%S.%f"
    else:
        fmt = "%Y-%m-%d %H:%M:%S"

    try:
        return datetime.strptime(value, fmt)
    except ValueError:
        return None


def is_ci_failure_message(text):
    """
    Détecte les échecs CI dans les messages Gerrit.
    On garde une définition simple mais plus large que l'ancien script.
    """
    text = str(text or "").lower()

    failure_patterns = [
        "verified-1",
        "verified -1",
        "verified-2",
        "verified -2",
        "build failed",
        "failure",
        "failed",
        "check failed",
    ]

    return any(pattern in text for pattern in failure_patterns)


def is_negative_human_vote(text):
    """
    Détecte les événements de vote négatif humain.

    Attention : cette métrique compte des événements de vote négatif,
    pas forcément des reviewers uniques opposés au changement.
    """
    text = str(text or "")

    negative_patterns = [
        "Code-Review-1",
        "Code-Review -1",
        "Code-Review-2",
        "Code-Review -2",
        "Workflow-1",
        "Workflow -1",
        "Verified-1",
        "Verified -1",
    ]

    return any(pattern in text for pattern in negative_patterns)



def empty_metrics(status):
    """
    Retourne un dictionnaire vide mais structuré.
    """
    return {
        "patchsets": None,
        "human_messages": None,
        "human_reviewers": None,
        "review_duration_days": None,
        "review_hours": None,
        "ci_failures": None,
        "human_negative_votes": None,
        "api_status": status,
    }


def fetch_gerrit_metrics(url, cache):
    """
    Récupère les métriques Gerrit pour un changement donné.

    Améliorations principales :
    - utilise ALL_REVISIONS pour compter les patchsets ;
    - utilise submitted - created si submitted existe ;
    - détecte mieux les bots ;
    - ajoute un statut API ;
    - utilise un cache pour éviter les appels répétés.
    """
    url = str(url)

    if url in cache:
        return cache[url]

    numeric_id = get_numeric_id(url)
    if not numeric_id:
        result = empty_metrics("missing_or_invalid_url")
        cache[url] = result
        return result

    api_url = (
        f"https://review.opendev.org/changes/{numeric_id}/detail"
        f"?o=MESSAGES"
        f"&o=DETAILED_ACCOUNTS"
        f"&o=ALL_REVISIONS"
    )

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = session.get(api_url, timeout=30)

            if response.status_code == 429:
                if attempt < MAX_RETRIES:
                    time.sleep(5 * attempt)
                    continue

                result = empty_metrics("rate_limited")
                cache[url] = result
                return result

            if response.status_code == 404:
                result = empty_metrics("not_found")
                cache[url] = result
                return result

            if response.status_code != 200:
                result = empty_metrics(f"http_{response.status_code}")
                cache[url] = result
                return result

            try:
                data = json.loads(clean_gerrit_json(response.text))
            except json.JSONDecodeError:
                result = empty_metrics("json_parse_error")
                cache[url] = result
                return result

           
            revisions = data.get("revisions", {})
            patchsets = len(revisions) if isinstance(revisions, dict) else None

            # Fallback si revisions est absent
            if not patchsets:
                patchsets = 1

            human_messages = 0
            ci_failures = 0
            human_negative_votes = 0

            messages = data.get("messages", [])

            for msg in messages:
                author = msg.get("author", {})
                author_name = author.get("name", "")
                tag = msg.get("tag", "")
                text = msg.get("message", "")

                if is_bot(author_name, tag):
                    if is_ci_failure_message(text):
                        ci_failures += 1
                else:
                    human_messages += 1

                    if is_negative_human_vote(text):
                        human_negative_votes += 1

           
            human_reviewers = set()
            reviewers_dict = data.get("reviewers", {})

            if isinstance(reviewers_dict, dict):
                for _, reviewer_list in reviewers_dict.items():
                    for reviewer in reviewer_list:
                        name = reviewer.get("name", "")
                        email = reviewer.get("email", "")

                        reviewer_id = email or name

                        if reviewer_id and not is_bot(name):
                            human_reviewers.add(reviewer_id)

            
            created_dt = parse_gerrit_datetime(data.get("created"))
            submitted_dt = parse_gerrit_datetime(data.get("submitted"))
            updated_dt = parse_gerrit_datetime(data.get("updated"))

            review_duration_days = None
            review_hours = None

            # Meilleur cas : durée jusqu'au merge
            if created_dt and submitted_dt:
                seconds = max(0, (submitted_dt - created_dt).total_seconds())
                review_duration_days = round(seconds / 86400.0, 2)
                review_hours = round(seconds / 3600.0, 2)

            # Fallback : dernière activité
            elif created_dt and updated_dt:
                seconds = max(0, (updated_dt - created_dt).total_seconds())
                review_duration_days = round(seconds / 86400.0, 2)
                review_hours = round(seconds / 3600.0, 2)

            result = {
                "patchsets": patchsets,
                "human_messages": human_messages,
                "human_reviewers": len(human_reviewers),
                "review_duration_days": review_duration_days,
                "review_hours": review_hours,
                "ci_failures": ci_failures,
                "human_negative_votes": human_negative_votes,
                "api_status": "ok",
            }

            cache[url] = result
            return result

        except requests.exceptions.RequestException:
            if attempt < MAX_RETRIES:
                time.sleep(2 * attempt)
                continue

            result = empty_metrics("request_error")
            cache[url] = result
            return result

    result = empty_metrics("unknown_error")
    cache[url] = result
    return result

def ensure_columns(df):
    """
    Ajoute les colonnes manquantes au dataset.
    """
    for col in METRIC_COLUMNS:
        if col not in df.columns:
            df[col] = pd.NA

    return df


def row_already_processed(row):
    """
    Ignore une ligne si les deux appels API ont déjà réussi.
    Pratique si tu relances le script après une interruption.
    """
    return (
        str(row.get("master_api_status", "")) == "ok"
        and str(row.get("bp_api_status", "")) == "ok"
    )


def write_metrics_to_row(df, index, prefix, metrics):
    """
    Écrit les métriques dans les colonnes master_* ou bp_*.
    """
    df.at[index, f"{prefix}_patchsets"] = metrics["patchsets"]
    df.at[index, f"{prefix}_human_messages"] = metrics["human_messages"]
    df.at[index, f"{prefix}_human_reviewers"] = metrics["human_reviewers"]
    df.at[index, f"{prefix}_review_duration_days"] = metrics["review_duration_days"]
    df.at[index, f"{prefix}_review_hours"] = metrics["review_hours"]
    df.at[index, f"{prefix}_ci_failures"] = metrics["ci_failures"]
    df.at[index, f"{prefix}_human_negative_votes"] = metrics["human_negative_votes"]

    if prefix == "master":
        df.at[index, "master_api_status"] = metrics["api_status"]
    elif prefix == "bp":
        df.at[index, "bp_api_status"] = metrics["api_status"]


def main():
    print(f"Chargement du dataset : {INPUT_FILE}")

    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(f"Fichier introuvable : {INPUT_FILE}")

    df = pd.read_csv(INPUT_FILE)
    df = ensure_columns(df)

    cache = {}

    print(f"Nombre de paires à traiter : {len(df)}")
    print(f"Fichier de sortie : {OUTPUT_FILE}")

    for index, row in tqdm(df.iterrows(), total=len(df)):
        if row_already_processed(row):
            continue

        master_url = row.get("master_patch_url")
        bp_url = row.get("stable_backport_url")

        master_metrics = fetch_gerrit_metrics(master_url, cache)
        time.sleep(SLEEP_BETWEEN_CALLS)

        bp_metrics = fetch_gerrit_metrics(bp_url, cache)
        time.sleep(SLEEP_BETWEEN_CALLS)

        write_metrics_to_row(df, index, "master", master_metrics)
        write_metrics_to_row(df, index, "bp", bp_metrics)

        if index > 0 and index % SAVE_EVERY == 0:
            df.to_csv(OUTPUT_FILE, index=False)
            print(f"Sauvegarde intermédiaire à la ligne {index}")

    df.to_csv(OUTPUT_FILE, index=False)

    print("\nTerminé.")
    print(f"Dataset enrichi sauvegardé dans : {OUTPUT_FILE}")
    print("Le dataset original n'a pas été modifié.")


if __name__ == "__main__":
    main()